import { Router } from "express";
import AccountController from "../../controllers/admin/AccountController";
import AccountService from "../../services/AccountService";
import RoleService from "../../services/RoleService";
import { paginationMiddleware } from "../../middlewares/pagination";
const router: Router = Router();
const accountService = new AccountService();
const roleService = new RoleService();
const accountController = new AccountController();
accountController.addRevide("accountService", accountService);
accountController.addRevide("roleService", roleService);
router.get("/create-account", accountController.showView);
router.get("/update-account/:id", accountController.showView);
router.get("/accounts", paginationMiddleware, accountController.showView);
router.post("/create-account", accountController.create);
router.patch("/update-account/:id", accountController.update);
router.delete("/delete-account/:id", accountController.delete);
export default router;
