import { Router } from "express";
import ActorController from "../../controllers/admin/ActorController";
import ActorService from "../../services/ActorService";
import { uploadImage } from "../../middlewares/uploadCloud";
import { paginationMiddleware } from "../../middlewares/pagination";
const actorService = new ActorService();
const actorController = new ActorController(actorService);
const router: Router = Router();
router.get("/create-actor", actorController.showView);
router.get("/update-actor/:id", actorController.showView);
router.get("/actors", paginationMiddleware, actorController.showView);
router.post("/create-actor", uploadImage.single("actor_image"), actorController.create);
router.patch("/update-actor/:id", uploadImage.single("actor_image"), actorController.update);
router.delete("/delete-actor/:id", actorController.delete);
export default router;
