import { Router } from "express";
import CategoryController from "../../controllers/admin/CategoryController";
import CategoryService from "../../services/CategoryService";
import { paginationMiddleware } from "../../middlewares/pagination";
const categoryService = new CategoryService();
const categoryController = new CategoryController(categoryService);
const router: Router = Router();
router.get("/create-category", categoryController.showView);
router.get("/update-category/:id", categoryController.showView);
router.get("/categories", paginationMiddleware, categoryController.showView);
router.post("/create-category", categoryController.create);
router.patch("/update-category/:id", categoryController.update);
router.delete("/delete-category/:id", categoryController.delete);
export default router;
