import express, { Router } from "express";
import MovieService from "../services/admin/MovieService";
import ActorService from "../services/admin/ActorService";
import MovieController from "../controllers/admin/MovieController";
import CategoryService from "../services/admin/CategoryService";
import uploadMedia from "../middlewares/uploadCloud";
import { handleMulterError } from "../middlewares/handleMulterError";
const router: Router = express.Router();
const movieService = new MovieService();
const actorService = new ActorService();
const categoryService = new CategoryService();
const movieController = new MovieController();
movieController.addRevide(movieService);
movieController.addRevide(actorService);
movieController.addRevide(categoryService);
router.get("/create-movie", movieController.showView);
router.post("/create-movie", handleMulterError(uploadMedia), movieController.createMovie);
export default router;
